services:
  db:
    image: postgres:15-alpine
    container_name: proxy-sth-db
    environment:
      POSTGRES_DB: proxydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d proxydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build: .
    container_name: proxy-sth-app
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=proxydb
      - DB_USER=postgres
      - DB_PASS=postgrespassword
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
